package com.ericsson.graduate.microservices.gerrit;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.web.client.RestTemplate;

@SpringBootApplication
public class GerritMSApplication {
    public static void main(String[] args) {
        SpringApplication.run(GerritMSApplication.class, args);
    }

    @Bean
    public RestTemplate restTemplate(RestTemplateBuilder builder) {
        return builder
                //  Autogenerated from gerrit
                .basicAuthentication("ebeecon", "Jhg4q3KgGKeH3p/S3c1eb1RHX9saX4adHv0cYwYL9A")
                .build();
    }
}
